### PR TITLE
Ensure we close the body to avoid deadlock error

### PR DESCRIPTION
**Pull request by xentek**
This commit is should fix the "ThreadError; deadlock; recursive locking" error was reported in #4, though I am not certain of it yet as I only get this error intermittently.

I'm running this patch in production right now and have a search on my logs set up to notify me if the error occurs again. I'll report my results back in a few days.

At a minimum, this change does not seem to interfere with the gem's normal functionality, and should be safe to merge.

### CODE REVIEW

**Comment by xentek** [comment]
So far... no incidents. I believe this patch fixes the deadlock issue.

**Comment by xentek** [comment]
@mattolson I've continued to monitor this closely and I can confirm that it does indeed fix the deadlock issue

**Comment by mattolson** [comment]
@xentek Thank you!

**Comment by xentek** [comment]
@mattolson Awesome! Don't forget to bump and release a new version of the gem, when you get a second. That way I can stop pulling it from `git` in my projects :)

**Comment by mattolson** [comment]
@xentek version 1.0.1 released

**Comment by xentek** [comment]
Sweet. Thanks for doing that.

**Pull request merged**
